os: linux
node_js: '12'
sudo: required
env: DISPLAY=':99.0'
dist: trusty
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable

before_script:
  - sh -e /etc/init.d/xvfb start

addons:
  apt:
+   update: true
    sources:
     - google-chrome
    packages:
+    - dpkg
     - google-chrome-stable
